bot_token: 
bot_prefix: /
command_title: Commands
commands:
  - "`/+say channelName [message to send to channel]`"
  - "Activate message sending to MentionedChannel. All messages you send hereafter will be send to this channel"
  - "`/-say`"
  - "Deactivate message sending to MentionChannel"
  - "`/delete`"
  - "Delete last sent message while say is active"
  - "`/jokeHere`"
  - "Post a joke in current channel"
  - "`/jokeThere MentionChannel`"
  - "Send joke to the MentionedChannel"
  - "`/factsHere`"
  - "Post facts in current channel"
  - "`/factsThere MentionChannel`"
  - "Send facts to the MentionedChannel"
  - "`/help`"
